// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaModerna.Infrastructure.Data;

#nullable disable

namespace TiendaModerna.Infrastructure.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Remeras deportivas y casuales",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 412, DateTimeKind.Utc).AddTicks(9518),
                            Nombre = "Remeras",
                            Orden = 0,
                            Slug = "remeras"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Pantalones deportivos y casuales",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 412, DateTimeKind.Utc).AddTicks(9520),
                            Nombre = "Pantalones",
                            Orden = 0,
                            Slug = "pantalones"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Camperas y abrigos deportivos",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 412, DateTimeKind.Utc).AddTicks(9522),
                            Nombre = "Camperas",
                            Orden = 0,
                            Slug = "camperas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Calzado deportivo de alta calidad",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 412, DateTimeKind.Utc).AddTicks(9523),
                            Nombre = "Zapatillas",
                            Orden = 0,
                            Slug = "zapatillas"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Accesorios deportivos y complementos",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 412, DateTimeKind.Utc).AddTicks(9525),
                            Nombre = "Accesorios",
                            Orden = 0,
                            Slug = "accesorios"
                        });
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.DetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DetalleVariante")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VarianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VarianteId");

                    b.ToTable("DetallesOrdenes");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TextoAlternativo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Just Do It",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(182),
                            Nombre = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Impossible is Nothing",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(183),
                            Nombre = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Forever Faster",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(185),
                            Nombre = "Puma"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "I Will",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(186),
                            Nombre = "Under Armour"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Be More Human",
                            EstaActiva = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(187),
                            Nombre = "Reebok"
                        });
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodigoCupon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodigoSeguimiento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DireccionEnvio2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmpresaTransporte")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdTransaccionPago")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NotasCliente")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadStock")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("EsDestacado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoSKU")
                        .IsUnique();

                    b.HasIndex("MarcaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadStock = 50,
                            CategoriaId = 1,
                            CodigoSKU = "REM-NIKE-001",
                            Descripcion = "Remera deportiva de alta calidad con tecnología Dri-FIT",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(254),
                            MarcaId = 1,
                            Nombre = "Nike Deportiva Remera",
                            PorcentajeDescuento = 0m,
                            PrecioBase = 8500m
                        },
                        new
                        {
                            Id = 2,
                            CantidadStock = 45,
                            CategoriaId = 1,
                            CodigoSKU = "REM-ADIDAS-001",
                            Descripcion = "Remera de entrenamiento con tecnología Climacool",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(257),
                            MarcaId = 2,
                            Nombre = "Adidas Performance Remera",
                            PorcentajeDescuento = 0m,
                            PrecioBase = 7900m
                        },
                        new
                        {
                            Id = 3,
                            CantidadStock = 30,
                            CategoriaId = 2,
                            CodigoSKU = "PANT-NIKE-001",
                            Descripcion = "Pantalón deportivo con tecnología Fleece para mayor comodidad",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(300),
                            MarcaId = 1,
                            Nombre = "Nike Tech Fleece Pantalón",
                            PorcentajeDescuento = 20m,
                            PrecioBase = 15000m
                        },
                        new
                        {
                            Id = 4,
                            CantidadStock = 25,
                            CategoriaId = 4,
                            CodigoSKU = "ZAP-NIKE-001",
                            Descripcion = "Zapatillas con amortiguación Air Max para máximo confort",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(303),
                            MarcaId = 1,
                            Nombre = "Nike Air Max Zapatillas",
                            PorcentajeDescuento = 0m,
                            PrecioBase = 35000m
                        },
                        new
                        {
                            Id = 5,
                            CantidadStock = 20,
                            CategoriaId = 4,
                            CodigoSKU = "ZAP-ADIDAS-001",
                            Descripcion = "Zapatillas con tecnología Boost para máxima respuesta",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(305),
                            MarcaId = 2,
                            Nombre = "Adidas Ultraboost Zapatillas",
                            PorcentajeDescuento = 20m,
                            PrecioBase = 38000m
                        },
                        new
                        {
                            Id = 6,
                            CantidadStock = 35,
                            CategoriaId = 3,
                            CodigoSKU = "CAMP-PUMA-001",
                            Descripcion = "Campera deportiva cortavientos",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(308),
                            MarcaId = 3,
                            Nombre = "Puma Performance Campera",
                            PorcentajeDescuento = 15m,
                            PrecioBase = 22000m
                        },
                        new
                        {
                            Id = 7,
                            CantidadStock = 60,
                            CategoriaId = 5,
                            CodigoSKU = "ACC-NIKE-001",
                            Descripcion = "Mochila deportiva con múltiples compartimentos",
                            EsDestacado = false,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(310),
                            MarcaId = 1,
                            Nombre = "Nike Brasilia Mochila",
                            PorcentajeDescuento = 0m,
                            PrecioBase = 12000m
                        },
                        new
                        {
                            Id = 8,
                            CantidadStock = 55,
                            CategoriaId = 1,
                            CodigoSKU = "REM-PUMA-001",
                            Descripcion = "Remera básica de algodón",
                            EsDestacado = false,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(312),
                            MarcaId = 3,
                            Nombre = "Puma Essential Remera",
                            PorcentajeDescuento = 0m,
                            PrecioBase = 6500m
                        },
                        new
                        {
                            Id = 9,
                            CantidadStock = 40,
                            CategoriaId = 4,
                            CodigoSKU = "ZAP-REEBOK-001",
                            Descripcion = "Zapatillas clásicas de cuero",
                            EsDestacado = true,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(314),
                            MarcaId = 5,
                            Nombre = "Reebok Classic Leather",
                            PorcentajeDescuento = 20m,
                            PrecioBase = 18000m
                        },
                        new
                        {
                            Id = 10,
                            CantidadStock = 42,
                            CategoriaId = 2,
                            CodigoSKU = "PANT-ADIDAS-001",
                            Descripcion = "Pantalón de entrenamiento clásico",
                            EsDestacado = false,
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 10, 31, 16, 59, 3, 413, DateTimeKind.Utc).AddTicks(317),
                            MarcaId = 2,
                            Nombre = "Adidas Tiro Pantalón",
                            PorcentajeDescuento = 0m,
                            PrecioBase = 13000m
                        });
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CiudadPredeterminada")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodigoPostalPredeterminado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DireccionPredeterminada")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProvinciaPredeterminada")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("TokenRecuperacionExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenVerificacionEmail")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("TokenVerificacionExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UltimoInicioSesion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Variante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AjustePrecio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantidadStock")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSKU")
                        .IsUnique();

                    b.HasIndex("ProductoId");

                    b.ToTable("Variantes");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("TiendaModerna.Domain.Entities.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreId");

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.DetalleOrden", b =>
                {
                    b.HasOne("TiendaModerna.Domain.Entities.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiendaModerna.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesOrdenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiendaModerna.Domain.Entities.Variante", "Variante")
                        .WithMany()
                        .HasForeignKey("VarianteId");

                    b.Navigation("Orden");

                    b.Navigation("Producto");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Imagen", b =>
                {
                    b.HasOne("TiendaModerna.Domain.Entities.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Orden", b =>
                {
                    b.HasOne("TiendaModerna.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ordenes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Producto", b =>
                {
                    b.HasOne("TiendaModerna.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiendaModerna.Domain.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Variante", b =>
                {
                    b.HasOne("TiendaModerna.Domain.Entities.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallesOrdenes");

                    b.Navigation("Imagenes");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("TiendaModerna.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
