# Generated by Django 4.1.7 on 2025-10-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cardio', 'Cardiovascular'), ('strength', 'Fuerza'), ('flexibility', 'Flexibilidad'), ('balance', 'Equilibrio'), ('hiit', 'HIIT')], max_length=50)),
                ('calories_per_hour', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=50)),
                ('instructions', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='exercise_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='calories_burn_rate',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentario'), ('light', 'Actividad ligera'), ('moderate', 'Actividad moderada'), ('very_active', 'Muy activo'), ('extra_active', 'Extra activo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Pérdida de peso'), ('muscle_gain', 'Ganancia muscular'), ('endurance', 'Resistencia'), ('flexibility', 'Flexibilidad'), ('general_fitness', 'Fitness general')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(help_text='Duración en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(help_text='Altura en centímetros', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(help_text='Peso en kilogramos', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='exercise_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workoutplan'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('admin', 'Administrador'), ('coach', 'Entrenador')], max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'team')},
            },
        ),
    ]
